package com.google.android.gms.internal;

import android.support.annotation.NonNull;
import android.support.annotation.Nullable;
import com.google.android.gms.common.api.AbstractC4494i;
import com.google.android.gms.common.api.AbstractC4502m;
import com.google.android.gms.common.api.AbstractC4503n;
import com.google.android.gms.common.api.AbstractC4505p;
import com.google.android.gms.common.api.AbstractC4506q;
import com.google.android.gms.common.api.Status;
import com.google.android.gms.common.internal.C4588d;
import java.util.concurrent.TimeUnit;
/* loaded from: classes2.dex */
public class ais<R extends AbstractC4502m> extends AbstractC4494i<R> {

    /* renamed from: a */
    private final Status f21953a;

    public ais(Status status) {
        C4588d.m23626a(status, "Status must not be null");
        C4588d.m23618b(!status.m24018f(), "Status must not be success");
        this.f21953a = status;
    }

    @Override // com.google.android.gms.common.api.AbstractC4494i
    @NonNull
    /* renamed from: a */
    public R mo13675a(long j, @NonNull TimeUnit timeUnit) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // com.google.android.gms.common.api.AbstractC4494i
    @NonNull
    /* renamed from: a */
    public <S extends AbstractC4502m> AbstractC4506q<S> mo17196a(@NonNull AbstractC4505p<? super R, ? extends S> abstractC4505p) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // com.google.android.gms.common.api.AbstractC4494i
    /* renamed from: a */
    public void mo13676a() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // com.google.android.gms.common.api.AbstractC4494i
    /* renamed from: a */
    public void mo17197a(@NonNull AbstractC4494i.AbstractC4495a abstractC4495a) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // com.google.android.gms.common.api.AbstractC4494i
    /* renamed from: a */
    public void mo13673a(@NonNull AbstractC4503n<? super R> abstractC4503n) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // com.google.android.gms.common.api.AbstractC4494i
    /* renamed from: a */
    public void mo13672a(@NonNull AbstractC4503n<? super R> abstractC4503n, long j, @NonNull TimeUnit timeUnit) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    /* JADX INFO: Access modifiers changed from: package-private */
    @NonNull
    /* renamed from: b */
    public Status m17195b() {
        return this.f21953a;
    }

    @Override // com.google.android.gms.common.api.AbstractC4494i
    @NonNull
    /* renamed from: d */
    public R mo13671d() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // com.google.android.gms.common.api.AbstractC4494i
    /* renamed from: e */
    public boolean mo13670e() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override // com.google.android.gms.common.api.AbstractC4494i
    @Nullable
    /* renamed from: f */
    public Integer mo17194f() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }
}
